#!/bin/bash

get_archive_folder()
{
        possible_matches=$(find "${email_archive_folder}" -maxdepth 1 -type d | grep "${email_address}_archive") || exit 1

        number_of_possible_matches=$(echo "${possible_matches}" | wc -l) || exit 1

        test "${number_of_possible_matches}" -eq "1" || exit 1

        echo "${possible_matches}"
}
