#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"        # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in

source "${DIR}"/bash_import_set_defaults                # set -o nounset; set -o errtrace; set -o errexit; set -o pipefail
source "${DIR}"/bash_import_lock_unique_cmd_line        # implements locking so that two identical command lines can not run at the same time.
source "${DIR}"/bash_import_email_archive_folder        # defines email_archive_folder

scriptname=`basename "$0"`
argcount=2
usage="user@domain.com [alot/emacs]"

test "$#" -le "${argcount}" || { echo "$0 ${usage}" && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="
test "$#" -ge "1" || { echo "$0 ${usage}" && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="

email_address="${1}"


source "${DIR}"/bash_import_get_archive_folder #must be done after email_address is set
#defines get_archive_folder()

archive_folder=$(get_archive_folder)

notmuch_folder="${archive_folder}/_notmuch"

printf "\033]0;${email_address}\007"

make_alot_config()
{
cat <<EOF

# config section for sending mail

[accounts]
	[[default]]
		realname = ${email_address}
		address = ${email_address}
		sendmail_command = ${DIR}/email_send ${email_address}


# to send a mail in alot enter the compose command http://alot.readthedocs.org/en/latest/usage/index.html#commands
# type
# :compose [ENTER]

[general]
hooksfile = ~/.config/alot/hooks.py

EOF
}


start_alot()
{
	alot --version || exit 1
	alot_config=$(make_alot_config) || exit 1
	echo "${alot_config}" > /dev/shm/__alot_config_"${email_address}" || exit 1
	alot --debug-level=debug --logfile=/dev/shm/__alot_log -n "${notmuch_folder}"/.notmuch-config_"${email_address}" -p "${archive_folder}"/_Maildirs -c /dev/shm/__alot_config_"${email_address}"
#	alot --debug-level=debug --logfile=/dev/shm/__alot_log -n "${notmuch_folder}"/.notmuch-config_"${email_address}" -p "${archive_folder}"/_Maildirs -c <(echo "${alot_config}")
}

start_emacs()
{
	{ export NOTMUCH_CONFIG="${notmuch_folder}/.notmuch-config_${email_address}" && emacs -f notmuch ; } &
}


client_type="${2-alot}"

if [[ "${client_type}" == "alot" ]];
then
	start_alot
elif [[ "${client_type}" == "emacs" ]];
then
	start_emacs
else
	echo "you could specify alot or emacs... starting alot"
	start_alot
fi

