#!/bin/bash

# requires: http://www.guru-group.fi/~too/nottoomuch/nottoomuch-addresses/

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"        # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in

source "${DIR}"/bash_import_set_defaults                # set -o nounset; set -o errtrace; set -o errexit; set -o pipefail
source ~/cfg/bash_libs/shell_command_lock/shell_command_lock # implements locking so that two identical command lines can not run at the same time.

scriptname=`basename "$0"`
min_argcount=1
usage="mode=update_notmuch_db/query_address_db/build_address_db/update_address_db/custom/notmuch) user@domain.com [querystring]"

test "$#" -ge "${min_argcount}" || { echo -e "Too few arguments\n$0 ${usage}" && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="

mode=`echo "${1}" | cut -d '=' -f 2`
shift

email_address="${1}"
username=$(echo "${email_address}" | cut -d '@' -f 1)
shift

echo "mode=$mode"

email_archive_folder=/home/user/__email_folders

notmuch_config_folder="${email_archive_folder}/_notmuch_config"

test -d "${notmuch_config_folder}" || { echo "${notmuch_config_folder} not found or is not a directory, exiting" && exit 1 ;}

touch "${notmuch_config_folder}"/.dir_write_test && rm "${notmuch_config_folder}"/.dir_write_test || { echo "${notmuch_config_folder} not writable, exiting" && exit 1 ;}


configure_notmuch()
{
cat <<EOF
[database]
path=${email_archive_folder}/_Maildirs

[user]
name=${username}
primary_email=${email_address}

[new]
tags=unread;inbox;

[maildir]
synchronize_flags=false
EOF
}


create_notmuch_config()
{
	configure_notmuch > "${NOTMUCH_CONFIG}"
}


NOTMUCH_CONFIG="${notmuch_config_folder}/.notmuch-config"
echo "${NOTMUCH_CONFIG}"

test -s "${NOTMUCH_CONFIG}" || { echo "making ${NOTMUCH_CONFIG}" && create_notmuch_config ; }


if [[ "${mode}" == "update_notmuch_db" ]]
then
	NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" notmuch new || exit 1

elif [[ "${mode}" == "custom" ]]
then
	echo "$NOTMUCH_CONFIG"
	NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" notmuch search --output=files "id:<1331789904.35708.YahooMailNeo@web39304.mail.mud.yahoo.com>" || exit 1

elif [[ "${mode}" == "notmuch" ]]
then
	echo "$NOTMUCH_CONFIG"
	NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" notmuch "$@" || exit 1

elif [[ "${mode}" == "query_address_db" ]]
then
#	echo "$@" >> /home/user/query
	XDG_CONFIG_HOME="${notmuch_config_folder}" NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" "${DIR}"/nottoomuch-addresses.sh "${1}"

elif [[ "${mode}" == "build_address_db" ]]
then
	XDG_CONFIG_HOME="${notmuch_config_folder}" NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" "${DIR}"/nottoomuch-addresses.sh --update --rebuild

elif [[ "${mode}" == "update_address_db" ]]
then
	XDG_CONFIG_HOME="${notmuch_config_folder}" NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" "${DIR}"/nottoomuch-addresses.sh --update

else
	echo "invalid mode ${mode}, exiting" && exit 1
fi

exit 0
