#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"        # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in

source "${DIR}"/bash_import_set_defaults                # set -o nounset; set -o errtrace; set -o errexit; set -o pipefail
source "${DIR}"/bash_import_lock_unique_cmd_line        # implements locking so that two identical command lines can not run at the same time.
source "${DIR}"/bash_import_email_archive_folder        # defines email_archive_folder

scriptname=`basename "$0"`
argcount=1
usage="user@domain.com"

test "$#" -eq "${argcount}" || { echo "$0 ${usage}" && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="

email_address="${1}"
username=$(echo "${email_address}" | cut -d '@' -f 1)

source "${DIR}"/bash_import_get_archive_folder #must be done after email_address is set
#defines get_archive_folder()

archive_folder=$(get_archive_folder)

notmuch_folder="${archive_folder}/_notmuch"

test -d "${notmuch_folder}" || { echo "${notmuch_folder} not found or is not a directory, exiting" && exit 1 ;}

touch "${notmuch_folder}"/.dir_write_test && rm "${notmuch_folder}"/.dir_write_test || { echo "${notmuch_folder} not writable, exiting" && exit 1 ;}


configure_notmuch()
{
cat <<EOF
[database]
path=${archive_folder}/_Maildirs

[user]
name=${username}
primary_email=${email_address}

[new]
tags=unread;inbox;

[maildir]
synchronize_flags=false
EOF
}


create_notmuch_config()
{
	configure_notmuch > "${NOTMUCH_CONFIG}"
}


NOTMUCH_CONFIG="${notmuch_folder}/.notmuch-config_${email_address}"
echo "${NOTMUCH_CONFIG}"

test -s "${NOTMUCH_CONFIG}" || { echo "making ${NOTMUCH_CONFIG}" && create_notmuch_config ; }

NOTMUCH_CONFIG="${NOTMUCH_CONFIG}" notmuch new || exit 1

exit 0
