#!/bin/bash

source shell_command_lock

echo "Checking for default-recipient in ~/.gnupg/gpg.conf"
grep "^default-recipient" ~/.gnupg/gpg.conf > /dev/null 2>&1 || { echo "default-recipient is not defined in ~/.gnupg/gpg.conf," ; exit 1 ; }


random_string()
{
        gpg2 --gen-random --armor 1 30
}

warm_up_gpg()
{
	#due to https://bugs.g10code.com/gnupg/issue1190 we must first get gpg-agent warmed up.
	#therefore we decrypt a dummy message.

	decrypt_test=0

	while [[ "${decrypt_test}" != "1" ]]; do
		echo "generating gpg test string"
		test_string=$(random_string) || fail "something went wrong generating a random test string"
		echo "warm_up_gpg test_string: ${test_string}"
		echo "warm_up_gpg() test_string: ${test_string}" | gpg --yes --trust-model always --throw-keyids --encrypt -o - | gpg --decrypt 2>&1 | grep "${test_string}" && decrypt_test=1
	done
	echo "done warming up gpg"
}

warm_up_gpg
